-- 1. Create the table safely
create table if not exists public.mottos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  language text not null,
  content text not null,
  author text not null
);

-- 2. Enable RLS (Safe to run multiple times)
alter table public.mottos enable row level security;

-- 3. Create Policy safely (Check existence before creating)
do $$
begin
  if not exists (
    select from pg_policies where tablename = 'mottos' and policyname = 'Enable read access for all users'
  ) then
    create policy "Enable read access for all users" on public.mottos for select using (true);
  end if;
end
$$;

-- 4. Insert Data (Only if table is empty to avoid duplicates)
insert into public.mottos (language, content, author)
select * from (values
  ('en', 'The only way to do great work is to love what you do.', 'Steve Jobs'),
  ('en', 'The expert in anything was once a beginner.', 'Helen Hayes'),
  ('en', 'Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
  ('en', 'Learning is a treasure that will follow its owner everywhere.', 'Chinese Proverb'),
  ('en', 'The beautiful thing about learning is that no one can take it away from you.', 'B.B. King'),
  ('pl', 'Jedynym sposobem na wielką pracę jest kochanie tego, co robisz.', 'Steve Jobs'),
  ('pl', 'Ekspert w każdej dziedzinie był kiedyś początkującym.', 'Helen Hayes'),
  ('pl', 'Uwierz, że potrafisz, a będziesz w połowie drogi.', 'Theodore Roosevelt'),
  ('pl', 'Nauka to skarb, który podąża za właścicielem wszędzie.', 'Przysłowie chińskie'),
  ('pl', 'Piękno nauki polega na tym, że nikt nie może ci jej odebrać.', 'B.B. King'),
  ('uk', 'Єдиний спосіб робити велику роботу - це любити те, що ти робиш.', 'Стів Джобс'),
  ('uk', 'Експерт у будь-якій справі колись був новачком.', 'Хелен Хейз'),
  ('uk', 'Повір, що ти можеш, і ти вже на півдорозі до мети.', 'Теодор Рузвельт'),
  ('uk', 'Навчання - це скарб, який буде слідувати за своїм власником всюди.', 'Китайське прислівʼя'),
  ('uk', 'Прекрасне в навчанні те, що ніхто не може його у вас відібрати.', 'Б.Б. Кінг')
) as v(language, content, author)
where not exists (
  select 1 from public.mottos limit 1
);